{{- range .Values.cronJobs }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
spec:
  schedule: "{{ .schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronjob-container
            image: "{{ $.Values.image.repository }}:{{ .version }}"
            command: ["node", "scripts/cronTask.js"]
          restartPolicy: OnFailure
{{- end }}
